"""Add fields duration, resolution and filesize in table download_history

Revision ID: 8ccd1c5949d4
Revises: bbd06aab0cad
Create Date: 2026-05-13 14:06:15.870552

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '8ccd1c5949d4'
down_revision: Union[str, Sequence[str], None] = 'bbd06aab0cad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('download_history', sa.Column('duration', sa.Integer(), nullable=True))
    op.add_column('download_history', sa.Column('resolution', sa.String(), nullable=True))
    op.add_column('download_history', sa.Column('filesize', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('download_history', 'filesize')
    op.drop_column('download_history', 'resolution')
    op.drop_column('download_history', 'duration')
    # ### end Alembic commands ###
