"""Create table download_history

Revision ID: 60c9986f0d7f
Revises:
Create Date: 2026-05-12 12:47:15.548164

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '60c9986f0d7f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'download_history',
        sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
        sa.Column('url', sa.String(), nullable=False),
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('thumbnail', sa.String(), nullable=True),
        sa.Column('profile', sa.String(), nullable=False),
        sa.Column('quality', sa.String(), nullable=True),
        sa.Column('file_path', sa.String(), nullable=True),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_download_history')),
    )
    op.create_index(op.f('ix_download_history_title'), 'download_history', ['title'], unique=False)
    op.create_index(
        op.f('ix_download_history_user_id'), 'download_history', ['user_id'], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_download_history_user_id'), table_name='download_history')
    op.drop_index(op.f('ix_download_history_title'), table_name='download_history')
    op.drop_table('download_history')
    # ### end Alembic commands ###
