"""Add params nullable in field title

Revision ID: bbd06aab0cad
Revises: 60c9986f0d7f
Create Date: 2026-05-12 18:49:17.416457

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "bbd06aab0cad"
down_revision: Union[str, Sequence[str], None] = "60c9986f0d7f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("download_history", "title", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("download_history", "title", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
