"""Add index for fields status and created_at

Revision ID: e2b5e7188dba
Revises: 8ccd1c5949d4
Create Date: 2026-06-26 02:36:48.670741

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'e2b5e7188dba'
down_revision: Union[str, Sequence[str], None] = '8ccd1c5949d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        'idx_download_history_status_created',
        'download_history',
        ['status', 'created_at'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_download_history_status_created', table_name='download_history')
    # ### end Alembic commands ###
